name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - name: build
        run: yarn build
      - name: push
        uses: EndBug/add-and-commit@v6.2.0
        with:
          message: 'release'
          add: 'build'
          branch: gh-pages