name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - name: build
        run: yarn build
      - name: push
        uses: Automattic/action-commit-to-branch@master
        with:
          commit_message: 'release'
          branch: 'gh-pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}